#pragma once

enum class eResTexture
{
	charactor_atlas_zero_black,
	charactor_atlas_zero_ori,
	charactor_atlas_zero_s,
	charactor_atlas_zero_virus,
	Chinatown01_spr_chinatown_parallax_1,
	Chinatown01_spr_chinatown_parallax_2,
	Chinatown01_spr_chinatown_parallax_3,
	Map_Chinatown04_Tilemap,
	Map_Chinatown05_spr_chinatown_loop_parallax_1,
	Map_Chinatown05_spr_chinatown_loop_parallax_2,
	Map_Chinatown05_Tilemap,
	Noise_01,
	Noise_02,
	Noise_03,
	Noise_04,
	TileMap_bg_club_background,
	TileMap_bg_haunted_background,
	Title_spr_titlegraphic_big2,
	Title_spr_titlegraphic_big_1,
	Title_spr_titlegraphic_big_2,
	Title_spr_title_background,
	Title_spr_title_fence,
	Title_spr_title_grass,
	Title_spr_title_plants_0,
	UI_spr_battery_part,
	UI_spr_cursor,
	UI_spr_hud,
	UI_spr_hud_battery,
	UI_spr_hud_subweapon,
	UI_spr_hud_timer_0,
	UI_spr_hud_timer_1,
	UI_spr_itemicons_0,
	UI_spr_katanaicons_0,
	UI_spr_keyboard_shift_0,
	UI_spr_keyboard_shift_1,
	UI_spr_left_click_1,
	UI_spr_right_click_1,
	UI_spr_timer,
	bg_bar_0,
	bg_cathedral_background_0,
	bg_club_full_0,
	bg_dreamshed_0,
	bg_studio_outside_0,
	chinatown1_test,
	door,
	map,
	orange,
	spr_bg_neighbor_apartment_0,
	TILE,
	walk,
	End
};

const wchar_t* EnumResourcePath(eResTexture type);

