#include "pch.h"
#include "EnumResourceTypeAudioClip.h"

static constexpr const wchar_t* eResAudioClipPath[static_cast<UINT>(eResAudioClip::End)]
{
	L"\\AudioClip\\actorDisinegrate.wav",
	L"\\AudioClip\\actorDisinegrate2.wav",
	L"\\AudioClip\\block.wav",
	L"\\AudioClip\\breakBlock.wav",
	L"\\AudioClip\\breakPipe.wav",
	L"\\AudioClip\\breakWood.wav",
	L"\\AudioClip\\bulletWhiz.wav",
	L"\\AudioClip\\cantThrow.wav",
	L"\\AudioClip\\doorOpen.wav",
	L"\\AudioClip\\enemySlice.wav",
	L"\\AudioClip\\enterGame.wav",
	L"\\AudioClip\\getItem.wav",
	L"\\AudioClip\\glassbreak.wav",
	L"\\AudioClip\\headBloodSpurt.wav",
	L"\\AudioClip\\headFloor.wav",
	L"\\AudioClip\\headWall.wav",
	L"\\AudioClip\\huntressbeam_circle.wav",
	L"\\AudioClip\\itemThrow.wav",
	L"\\AudioClip\\knifeDislodge.wav",
	L"\\AudioClip\\knifeWall.wav",
	L"\\AudioClip\\levelStart.wav",
	L"\\AudioClip\\playerCasettePlay.wav",
	L"\\AudioClip\\playerCasetteRewind.wav",
	L"\\AudioClip\\PlayerDie.wav",
	L"\\AudioClip\\playerFootStep.wav",
	L"\\AudioClip\\playerHeadphones.wav",
	L"\\AudioClip\\playerJump.wav",
	L"\\AudioClip\\playerKickDoor.wav",
	L"\\AudioClip\\playerLand.wav",
	L"\\AudioClip\\playerLandWire.wav",
	L"\\AudioClip\\playerPickUp.wav",
	L"\\AudioClip\\playerPreRun.wav",
	L"\\AudioClip\\playerRoll.wav",
	L"\\AudioClip\\playerSwordDraw.wav",
	L"\\AudioClip\\playerSwordQuickDraw.wav",
	L"\\AudioClip\\playerWallKick1.wav",
	L"\\AudioClip\\playerWallKick2.wav",
	L"\\AudioClip\\playerWallKick3.wav",
	L"\\AudioClip\\playerWallSlide.wav",
	L"\\AudioClip\\replayFF.wav",
	L"\\AudioClip\\replayPause.wav",
	L"\\AudioClip\\replayPlay.wav",
	L"\\AudioClip\\replayRew.wav",
	L"\\AudioClip\\rewind.wav",
	L"\\AudioClip\\slash1.wav",
	L"\\AudioClip\\slash2.wav",
	L"\\AudioClip\\slash3.wav",
	L"\\AudioClip\\slashBullet.wav",
	L"\\AudioClip\\slomoDisengage.wav",
	L"\\AudioClip\\slomoEngage.wav",
	L"\\AudioClip\\song_bossbattle.wav",
	L"\\AudioClip\\song_chinatown.wav",
	L"\\AudioClip\\song_fullconfession.wav",
	L"\\AudioClip\\start.wav",
	L"\\AudioClip\\throwableBullet.wav",
	L"\\AudioClip\\titleSplash.wav",
	L"\\AudioClip\\TransitionBegin.wav",
	L"\\AudioClip\\TransitionEnd.wav",
	L"\\AudioClip\\turretActivate.wav",
	L"\\AudioClip\\turretDeath.wav",
	L"\\AudioClip\\turretOverheat.wav",
	L"\\AudioClip\\tvThump.wav",
};

const wchar_t* EnumResourcePath(eResAudioClip type)
{
	return eResAudioClipPath[static_cast<UINT>(type)];
}

